apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: deny-batch-create
webhooks:
- name: deny.batch.create
  rules:
  - apiGroups:
    - "batch"
    apiVersions:
    - v1beta1
    operations:
    - "CREATE"
    resources:
    - cronjobs
  # Default failurePolicy is not fail.
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: default
      name: kube-vwh-service
      path: /deny-cronjob-create
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5UUTVPVGd6TURBM01CNFhEVEU1TURJeApNakUwTlRBd04xb1hEVEU1TURJeU1qRTBOVEF3T0Zvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFUwT1RrNE16QXdOekNDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWlEbHlJZ0hGeDRXSjdUdGVDdUlKWDFXQVBzeGFjT3JvbHpMWUpYNnR3dAo4QzI5Y2VQOURhS29wNFloS25aeGJDMlFCN0IycEpDQTZ0UDVDOS9LL1RXZWV2TkpGQmpKVnJ2VFk5M05NVk1lCnd6K1Fya1U4WkNuaEc1dEl2V3MxVldrRlVDU2NVOGhBRUUvemt5dXRhcjIzRm0xZ2pDWXgxTm5URCtYTThYbTUKS3Q2NEZ0Q0o5YUVPOUYza3BNWHRLL04zdDFJeDNTbkFaajdoU0g4b1AvbllhNzBrcEdwOVFiOWtVSUZzb1BPLwpqY1lsaFVwUEorRmRsTURnb0ZMS1pBR2lRRkN5NW1RdFFVa2JqN1dvYUNBY245NDd0OVRBSUZ1MzhibFJLVWlWClNpeCtVSkxxaU1wdkV3Ri9Qb3BrRXF6ZFU2eUhKcUV3UHRHSTQyaVg2Zk1DQXdFQUFhTWpNQ0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUV4VgpHWE5WQm40R2RNVkFxN2ZnWm9wZFdEdDhnMlhSS3o4ZDF6Y3ZBcEpHRGNCMklEd3NadVUxQW5CdndKSm5qTlJaCm1RMGdQdXFEalBNeFJ1dk1jUytoTElMYjJML0N1SHIrbStUb3N0MHNKQUR2RUh1NkovZHE1VFU4dUpUUEFheEcKdTJ2eXpndzAxT3NQeWpHUk9vZHQxWUUzYWZGK1FrT1BJY3BnYXliUGhlQmthNU1LeFNacHU5U0hSWWxkYTVQOQo0YVJHbUw1dEZXblJIcmxIUk01enk5eEoxbzdCdUhvTU5JMXhldkV4d2FVSWNIakxBaGsxRDBpSFArZ0FrR0ZzCkkwODQyYzhiWDcxaEFjaUFNSk5ndkp4a2dCZThOMkZ3WjlSY2JWb3hFR04raEQrWllXTlJyVVo4L0R3L282OUwKMkx2NG9vZXFPOERWK3V3ZjVLUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
