apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: deny-route-custom-create
webhooks:
- name: deny.route-custom.create
  rules:
  - apiGroups:
    - "batch"
    apiVersions:
    - v1beta1
    operations:
    - "CREATE"
    resources:
    - "*/*"
  # Default failurePolicy is not fail.
  failurePolicy: Fail
  clientConfig:
    url: "https://testing.michaelgugino.com/always-deny"
    # base64 encoded contents of a .pem cert file.
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6akNDQXJhZ0F3SUJBZ0lKQUswbzVJaE1jNDc3TUEwR0NTcUdTSWIzRFFFQkN3VUFNSHd4Q3pBSkJnTlYKQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpHVERFVk1CTUdBMVVFQnd3TVNtRmphM052Ym5acGJHeGxNUTh3RFFZRApWUVFLREFaTlIwTnZjbkF4RlRBVEJnTlZCQU1NRERFNU1pNHhOamd1TXprdU1URWhNQjhHQ1NxR1NJYjNEUUVKCkFSWVNiV2QxWjJsdWIwQnlaV1JvWVhRdVkyOXRNQjRYRFRFNU1ERXlNVEUwTkRreU9Wb1hEVEkwTURFeU1ERTAKTkRreU9Wb3dmREVMTUFrR0ExVUVCaE1DVlZNeEN6QUpCZ05WQkFnTUFrWk1NUlV3RXdZRFZRUUhEQXhLWVdOcgpjMjl1ZG1sc2JHVXhEekFOQmdOVkJBb01CazFIUTI5eWNERVZNQk1HQTFVRUF3d01NVGt5TGpFMk9DNHpPUzR4Ck1TRXdId1lKS29aSWh2Y05BUWtCRmhKdFozVm5hVzV2UUhKbFpHaGhkQzVqYjIwd2dnRWlNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQ1BzOFJiUGJkSWdmQTRGdU5kamtJWjhOYjBhN1NnSWk2R1Y2aQpBWFEvZUh5S0M4SUZtWnN4WmdmczBqTW82RlZlQktVMkwyMjJpdG5nNmFNVjlhTElQY256VG5BT2VKSkhzQUs5CnpmT0oyMFJuL2RjTUpiL2xwaE80WWIyVzJmd0krUHlqZXFEWGwzaU1leTI2N3cvWEFFME95YW1UTVJvOElWSCsKMG5oT2ZEUUpPeDVLTDFScW9HcEZkVXpEYmZKUDBsQURaTTRCNFR3T2lxbHlNRHJ5ZG8wcEMrR2NoUWpVSGhITApSR3V4Wi9tTWNlT0tOM3JETGNMbUlBM3pXUWM4dU5ZbzdocmNOcmU5bHR6NkN2eFZjS25ML1VqMmdSYnY5R3AzClhaaGltQ3dWM3JROEtXYWNISWpxWHZZK0hzcmJ3VnVKUXNMem1vOHczdmlJb1ZTZEFnTUJBQUdqVXpCUk1CMEcKQTFVZERnUVdCQlJ4RDg5UWtFam5KTVpUT2dBbkhaOCtGQWpvN1RBZkJnTlZIU01FR0RBV2dCUnhEODlRa0VqbgpKTVpUT2dBbkhaOCtGQWpvN1RBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQ3pxNWxqRE4zTTd1ZE9HSXlFNk9iOHRDTDNFUkdwT0FONlQ1SG5CN21Eem42T3FRQ1FzMm5MbFFOekxROHYKZ2h1Ym83OFNRRXNPZUZoZEpka0I1VjR6VTA4bGpDcFhnK2pIRllSU092Umh1MGQzMjFtSFpMaEVaQ2laSDJHeQpZRU9RUmhFOCtnRklsekhYZGJMMWdUSDROSXNza1kxaHRLUWZ6NkZ1MkNwdkhJbUNjaUpYZElycEYrazFieTd6CmFMYzZRbmVFbEpsQWRSSm5xOER4Nkt1TzJWSi80clc2dnI3cENZN3BJb2R3clEvbSt4MlExWUlqMW5TUE4zalAKa0J5Sm9iVDJSU3BneEZ3Y1Y3SmNpU0dvd3ladHdEYis2OGh5STlsdzhPTk1DV2JyR09xVVdUNGRpV0ZyK0FLMQplZm5FK2dKUWxrc0pZdmJmSDZ3dEFrZzQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
