apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: deny-pods-create
webhooks:
- name: deny.pods.create
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  # Default failurePolicy is not fail.
  failurePolicy: Fail
  clientConfig:
    url: "https://testing.michaelgugino.com/always-deny"
    # base64 encoded contents of a .pem cert file.
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVJJd0VBWURWUVFMRXdsdmNHVnUKYzJocFpuUXhFREFPQmdOVkJBTVRCM0p2YjNRdFkyRXdIaGNOTVRrd01qRXlNVFF6T1RFMFdoY05Namt3TWpBNQpNVFF6T1RFMFdqQW1NUkl3RUFZRFZRUUxFd2x2Y0dWdWMyaHBablF4RURBT0JnTlZCQU1UQjNKdmIzUXRZMkV3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM0d3ZGUS81bmc0YnlGNVhJVnpIWkIKWTRZbkVIN3RIQThZWENDYklXbG5FZTVwa0J6bFlkMDU3LzJrQjdjRVE4WmI0ZlhDQjZKY3VnR3hRNXUzUC9zUgpsV1JYZnpvK0ZNMWtZM3FYSzRWZndOQXJEaHpmdjBxODEzVG1DOW5yeFlVZEx2cUhnajhJVGRNT090RDRPaDR2ClVyMW1hWXdRWHJlai85RGxXTXorWHVvaENzQ2tuekh6SXM2YXlUUXBCdERBZ01ueGR0R3BvQlIzcXVLZmpWWHQKVGMyVVR5YlRIZHJaREVCc2JiOXdjYlBiYTVqOXJBUzBKTjlWam85K29ybnhrS2Vscmg1bHJGRjBsRTJ3dVVqawpIcloyY2pCU3k0WVFmWDcyQkNDYmlQa2owTlRBU3dOTXRITTdhdDFsdmlRT3dPZzYzeW16cDRGaWpoZ1JzTkdaCkFnTUJBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWQKRGdRV0JCVDdRRC9haW1FQmNONU5KcUdkOVhCME1LZHR4ekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQkxBQwp2ZVc3aURsOFgva1JFaWQ4MGFLY0JxWnBmQ2FSckdTcGQ3eTBKMVNRTnlZODZmQjlJVDJaNnNzR1FpcWFjM3BFCjk1bjdrdE5SUG5YbGZJQmZJbitEY0NReVc1NDVSV0ljdmNUKzUyRU81YjNRVEI4M0k5K212WVdoeFplSFVpMlcKSUJQT3VwOWVuMHhQWmpaSERsdlBJWnJrU1J2QWcvNjlLd3FqNzk5aE1oZUdJT2o5dEVkKzJuR3F3QndlZ1FkQQpFWk5KSzVOUTdvV0txVzVhdElIN0VqdDNhUFlVZ1R4ZU9UMUNsb0ZTQ2N0SWRocVBQUTkyeTVVb3RaKzdCRlg2Ckh4cUswdGlXREhia3lDamkwZ21UaThJVkExMmg0ajBZb2N3dC9EYjFDYVc3NXJqTS9Sb2Z0T0pLTkJDdVFHRlkKRlVPcGgydC9Ua0MveFcxdS9RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
